// Duck Sprite Constants
const DUCK_HEIGHT = 134;
const DUCK_WIDTH = 151.77;

// Player Constants
const DUCK_SPEED = 1.8;
const PLAYER_HEIGHT = 50;
const PLAYER_WIDTH = 40;
const PLAYER_BAT_HEIGHT = 40;
const PLAYER_BAT_WIDTH = 50;

// Bat Sprite Constants
const BAT_HEIGHT = 98;
const BAT_WIDTH = 148.125;
// 98;
// const BAT_WIDTH = 148.125;

// Map Constants
const MAP_WIDTH = 1920;
const MAP_HEIGHT = 1080;

export { DUCK_HEIGHT, DUCK_WIDTH, MAP_WIDTH, MAP_HEIGHT, DUCK_SPEED, PLAYER_HEIGHT, PLAYER_WIDTH, BAT_HEIGHT, BAT_WIDTH, PLAYER_BAT_HEIGHT, PLAYER_BAT_WIDTH}